services:
  db:
    image: mysql:8
    container_name: mysql8_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm
      MYSQL_USER: crm
      MYSQL_PASSWORD: crm
    ports:
      - "3306:3306"
    command : --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: